- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: cf550fcab3f12015f8676b8278b30e1a5bc10e70
  hooks:
  - id: trailing-whitespace
    exclude: ^spec/fixtures/
  - id: check-yaml
  - id: end-of-file-fixer
    exclude: ^spec/fixtures/
  - id: check-added-large-files
    args: [--maxkb=3000]
- repo: git://github.com/pricematch/mirrors-rubocop
  sha: 86353ba8a2785fc8b955bf20d30138927d8f59cf
  hooks:
  - id: rubocop
