# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4492f99f4aaa17559ee1ee30753c6445b9ad77f2def25aa69dd906ef9a0556c5a411eb8180e58dc40a430e04ebf9473804d3dc2f725d55bda68b8b94523838e7

test:
  secret_key_base: a717e581a605bddce1f8c97bc15822575c37a79cf4ee2bb9bca7629bac6391be69a8f6afa886af4b8fb62b22b7bf72cf533d6c6a179028ebb5061b9b1035f93a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
